### ISSUE TITLE
SecureCRT integration doesn't work

### ISSUE THREAD

**Issue by horseinthesky** [SmartFinn/eve-ng-integration#32] opened 2019-04-21 18:48 UTC
Hello.
I'm trying to change `/usr/bin/eve-ng-integration` script to be able to open new telnet sessions in SecureCRT tabs.

The correct shell command for this looks like this:
```
SecureCRT /T /telnet <host> <port>
```

So I've changed line 35 of the script to this:
```
       elif self._is_command('x-terminal-emulator'):
            return ['SecureCRT', '/T', '/telnet']
```
and line 90 to this:
```
        cmd = '{host} {port}'.format(**data)
```

So data for `Popen` on line 59 looks like this `[' SecureCRT', '/T', '/telnet', '192.168.0.11 32769']`

But it doesn't work though. It opens a new tab in SecureCRT with the name `192.168.0.11 32769` and `Connection refused` message.
But if I run it in the shell it works perfectly fine:
```
SecureCRT /T /telnet 192.168.0.11 32760
```
it opens new SecureCRT tab with `R1` router from the lab.

Could you help me with this?

**Comment by SmartFinn** [comment] 2019-04-23 04:51
Duplicate of #19

**Closed by SmartFinn** 2019-04-23 04:51 UTC
Labels: duplicate

**Comment by Fconffesor** [comment] 2021-02-10 13:20
@horseinthesky  thanks...! You give the missing tips for work:

you should edit "eve-ng-integration" script, in my case it is located in
/usr/bin/eve-ng-integration

elif self._is_command('x-terminal-emulator'):
            return ['SecureCRT', '/T', '/telnet']

cmd = '{host}:{port}'.format(**data)

The : is necesary to work.

Thanks to you and all.
