### ISSUE TITLE
Trying to install under OS X 11.6

### ISSUE THREAD

**Issue by OriWuKids** [SmartFinn/eve-ng-integration#26] opened 2018-07-03 16:39 UTC
ssh-askpass are available to OS X on https://github.com/theseal/ssh-askpass
but for vinagre,, it seems like a remote desktop program. I am still trying if its possible to replaced by other applications (from system's or 3rd parties VNC program).

And plus is there any intension for developing a client application under OS X environment?
Cheers.

**Comment by SmartFinn** [comment] 2018-07-03 16:58
Duplicate of #21

**Closed by SmartFinn** 2018-07-03 16:58 UTC
Labels: duplicate
