### ISSUE TITLE
MAC eve-NG can not use wireshark

### ISSUE THREAD

**Issue by haozhan3** [SmartFinn/eve-ng-integration#29] opened 2018-08-16 08:48 UTC
hi friend

i use MAC computer , want to use wireshark. folllow your document:
https://github.com/SmartFinn/eve-ng-integration#manual-install

MAC not support this command:
wget -qO- https://raw.githubusercontent.com/SmartFinn/eve-ng-integration/master/install.sh | sh

so i must manaul install. but follow manaul  process , will display error:
cd eve-ng-integration/eve-ng-integration-master
sudo make install

after issue "sudo make install" display below error:
HAOZHAN3-M-Q4RP:eve-ng-integration-master root# sudo make install
mkdir -p "/usr/bin"
install -m 755 bin/eve-ng-integration /usr/bin/
install: /usr/bin//eve-ng-integration: Operation not permitted
make: *** [install] Error 71

please help check the issue , thanks.

my email: 23421080@qq.com

**Comment by SmartFinn** [comment] 2018-08-16 09:10
Duplicate of #21

**Closed by SmartFinn** 2018-08-16 09:10 UTC
Labels: duplicate
